export const routeData = [
	{
		path: '/',
		heading: 'KiZush',
		bg_image: '/images/webaliser-_TPTXZd9mOo-unsplash.jpg',
		tagline: '',
		button_text: 'Read More',
		button_link: '',
	},
	{
		path: '/about',
		heading: 'About Us',
		bg_image:'https://baypointcontracting.ca/wp-content/uploads/2024/05/contact-zoomed-1240x645.jpg',
		tagline: '',
		button_text: 'Read More',
		button_link: '',
	},
	{
		path: '/service',
		heading: 'Our Services',
		bg_image: '/images/webaliser-_TPTXZd9mOo-unsplash.jpg',
		tagline: '',
		button_text: 'Read More',
		button_link: '',
	},
	{
		path: '/project',
		heading: 'Our Projects',
		bg_image:'https://baypointcontracting.ca/wp-content/uploads/2024/05/DSC_0669-Enhanced-NR-Custom.jpeg',
		tagline: '',
		button_text: 'Read More',
		button_link: '',
	},
	{
		path: '/resource',
		heading: 'Resources',
		bg_image:
			'https://baypointcontracting.ca/wp-content/uploads/2024/05/DSC_0669-Enhanced-NR-Custom.jpeg',
		tagline: '',
		button_text: 'Read More',
		button_link: '',
	},
	{
		path: '/contact',
		heading: 'Contact Us',
		bg_image:
			'https://baypointcontracting.ca/wp-content/uploads/2024/05/DSC_0669-Enhanced-NR-Custom-1200x800.jpeg',
		tagline: '',
		button_text: 'Read More',
		button_link: '',
	},
	{
		path: '/login',
		heading: 'Login',
		bg_image: '/images/webaliser-_TPTXZd9mOo-unsplash.jpg',
		tagline: '',
		button_text: 'Read More',
		button_link: '',
	},
];
